version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/NServiceBus.AttributeRouting.AcceptanceTests"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/NServiceBus.AttributeRouting.Tests"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/NServiceBus.AttributeRouting"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
